console.log("==================step1============");
var myFullName;
console.log("Before initialization---->",myFullName);
myFullName="Ashwini Magar";
console.log("after initialization---->",myFullName);
myFullName="Ashwini M Magar";
console.log("after update--->",myFullName);
console.log("==================step2============");
var myLove="I love only JS"
console.log("my love is ",myLove);
console.log("==================step3============");
var firstName="Ashwini";
console.log("my first name is--->",firstName);
var lastName="Magar";
console.log("my last name is--->",lastName);
var age="23";
console.log("my age is--->",age);
var address="navi Mumbai";
console.log("my address is--->",address);
var pincode="400705";
console.log("pincode is--->",pincode);
var gender="female";
console.log("gender is--->",gender);
var isMarried="Married";
console.log("is Married--->",isMarried);
